import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme/theme-provider";
import { ThemeToggle } from "@/components/ui/theme/theme-toggle";

export const metadata: Metadata = {
  title: "Spherity Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
